### ISSUE TITLE
v. 1.0.0 does not build with Boost 1.76

### ISSUE THREAD

**Issue by barracuda156** [kwin/macdependency#23]
@kwin Looks like this assumes some archaic version of Boost? Could we fix it to build with 1.76?

```
In file included from /opt/local/include/boost/process/detail/basic_cmd.hpp:10,
                 from /opt/local/include/boost/process/args.hpp:33,
                 from /opt/local/include/boost/process.hpp:22,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.h:5,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.cpp:1:
/opt/local/include/boost/process/detail/config.hpp:21:24: error: system_error: No such file or directory
In file included from /opt/local/include/boost/process/detail/basic_cmd.hpp:13,
                 from /opt/local/include/boost/process/args.hpp:33,
                 from /opt/local/include/boost/process.hpp:22,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.h:5,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.cpp:1:
/opt/local/include/boost/process/detail/traits/cmd_or_exe.hpp:12:23: error: type_traits: No such file or directory
/opt/local/include/boost/process/detail/traits/cmd_or_exe.hpp:13:28: error: initializer_list: No such file or directory
In file included from /opt/local/include/boost/process/detail/traits/wchar_t.hpp:13,
                 from /opt/local/include/boost/process/detail/basic_cmd.hpp:14,
                 from /opt/local/include/boost/process/args.hpp:33,
                 from /opt/local/include/boost/process.hpp:22,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.h:5,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.cpp:1:
/opt/local/include/boost/process/locale.hpp:16:19: error: codecvt: No such file or directory
In file included from /opt/local/include/boost/process/async.hpp:33,
                 from /opt/local/include/boost/process.hpp:23,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.h:5,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.cpp:1:
/opt/local/include/boost/process/detail/on_exit.hpp:17:18: error: future: No such file or directory
In file included from /opt/local/include/boost/process/detail/posix/async_pipe.hpp:10,
                 from /opt/local/include/boost/process/async_pipe.hpp:18,
                 from /opt/local/include/boost/process/detail/posix/async_in.hpp:16,
                 from /opt/local/include/boost/process/async.hpp:43,
                 from /opt/local/include/boost/process.hpp:23,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.h:5,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.cpp:1:
/opt/local/include/boost/process/detail/posix/basic_pipe.hpp:17:17: error: array: No such file or directory
In file included from /opt/local/include/boost/process/child.hpp:21,
                 from /opt/local/include/boost/process/async_system.hpp:22,
                 from /opt/local/include/boost/process.hpp:24,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.h:5,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.cpp:1:
/opt/local/include/boost/process/detail/child_decl.hpp:21:18: error: chrono: No such file or directory
/opt/local/include/boost/process/detail/child_decl.hpp:25:18: error: atomic: No such file or directory
In file included from /opt/local/include/boost/fusion/adapted/std_tuple/detail/begin_impl.hpp:11,
                 from /opt/local/include/boost/fusion/adapted/std_tuple.hpp:14,
                 from /opt/local/include/boost/process/detail/execute_impl.hpp:37,
                 from /opt/local/include/boost/process/child.hpp:22,
                 from /opt/local/include/boost/process/async_system.hpp:22,
                 from /opt/local/include/boost/process.hpp:24,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.h:5,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.cpp:1:
/opt/local/include/boost/fusion/adapted/std_tuple/std_tuple_iterator.hpp:17:17: error: tuple: No such file or directory
In file included from /opt/local/include/boost/process/environment.hpp:17,
                 from /opt/local/include/boost/process/env.hpp:9,
                 from /opt/local/include/boost/process.hpp:28,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.h:5,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.cpp:1:
/opt/local/include/boost/process/detail/posix/environment.hpp:11:25: error: unordered_map: No such file or directory
In file included from /opt/local/include/boost/process.hpp:39,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.h:5,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.cpp:1:
/opt/local/include/boost/process/system.hpp:27:17: error: mutex: No such file or directory
/opt/local/include/boost/process/system.hpp:28:30: error: condition_variable: No such file or directory
In file included from /opt/local/include/boost/process/detail/config.hpp:24,
                 from /opt/local/include/boost/process/detail/basic_cmd.hpp:10,
                 from /opt/local/include/boost/process/args.hpp:33,
                 from /opt/local/include/boost/process.hpp:22,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.h:5,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.cpp:1:
/opt/local/include/boost/process/exception.hpp:21: error: expected class-name before ‘{’ token
/opt/local/include/boost/process/exception.hpp:22: error: ‘std::system_error’ has not been declared
In file included from /opt/local/include/boost/process/detail/basic_cmd.hpp:10,
                 from /opt/local/include/boost/process/args.hpp:33,
                 from /opt/local/include/boost/process.hpp:22,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.h:5,
                 from /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.cpp:1:
/opt/local/include/boost/process/detail/config.hpp:50: error: ‘error_code’ in namespace ‘std’ does not name a type
/opt/local/include/boost/process/detail/config.hpp: In function ‘void boost::process::detail::throw_last_error(const std::string&)’:
/opt/local/include/boost/process/detail/config.hpp:76: error: ‘get_last_error’ was not declared in this scope
/opt/local/include/boost/process/detail/config.hpp: In function ‘void boost::process::detail::throw_last_error(const char*)’:
/opt/local/include/boost/process/detail/config.hpp:81: error: ‘get_last_error’ was not declared in this scope
/opt/local/include/boost/process/detail/config.hpp: In function ‘void boost::process::detail::throw_last_error()’:
/opt/local/include/boost/process/detail/config.hpp:86: error: ‘get_last_error’ was not declared in this scope
/opt/local/include/boost/process/detail/config.hpp: At global scope:
/opt/local/include/boost/process/detail/config.hpp:89: error: expected unqualified-id before ‘&’ token
/opt/local/include/boost/process/detail/config.hpp:89: error: expected ‘,’ or ‘...’ before ‘&’ token
/opt/local/include/boost/process/detail/config.hpp: In function ‘void boost::process::detail::throw_error()’:
/opt/local/include/boost/process/detail/config.hpp:91: error: ‘ec’ was not declared in this scope
/opt/local/include/boost/process/detail/config.hpp: At global scope:
/opt/local/include/boost/process/detail/config.hpp:95: error: expected unqualified-id before ‘&’ token
/opt/local/include/boost/process/detail/config.hpp:95: error: expected ‘,’ or ‘...’ before ‘&’ token
/opt/local/include/boost/process/detail/config.hpp: In function ‘void boost::process::detail::throw_error()’:
/opt/local/include/boost/process/detail/config.hpp:95: error: redefinition of ‘void boost::process::detail::throw_error()’
/opt/local/include/boost/process/detail/config.hpp:89: error: ‘void boost::process::detail::throw_error()’ previously defined here
/opt/local/include/boost/process/detail/config.hpp:97: error: ‘ec’ was not declared in this scope
/opt/local/include/boost/process/detail/config.hpp:98: error: ‘msg’ was not declared in this scope
. . .
/opt/local/include/boost/asio/detail/push_options.hpp:82: error: expected `}' before end of line
/opt/local/include/boost/asio/detail/push_options.hpp:82: error: expected declaration before end of line
** BUILD FAILED **

The following build commands failed:
MachO:
	CompileC /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MacDependency/build/MachO.build/Release/MachO.build/Objects-normal/ppc/internalfile.o /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/internalfile.cpp normal ppc c++ com.apple.compilers.gcc.4_2
	CompileC /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MacDependency/build/MachO.build/Release/MachO.build/Objects-normal/ppc/demangler.o /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/demangler.cpp normal ppc c++ com.apple.compilers.gcc.4_2
	CompileC /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MacDependency/build/MachO.build/Release/MachO.build/Objects-normal/ppc/macho.o /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/macho.cpp normal ppc c++ com.apple.compilers.gcc.4_2
	CompileC /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MacDependency/build/MachO.build/Release/MachO.build/Objects-normal/ppc/symboltableentry.o /opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO/symboltableentry.cpp normal ppc c++ com.apple.compilers.gcc.4_2
(4 failures)

Command failed: cd "/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MachO" && /usr/bin/xcodebuild -target "MachO" -configuration Deployment build  OBJROOT="/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MacDependency/build/" SYMROOT="/opt/local/var/macports/build/_opt_PPCSnowLeopardPorts_sysutils_macdependency/macdependency/work/macdependency-1.0.0/MacDependency/build/" MACOSX_DEPLOYMENT_TARGET=10.6 ARCHS=ppc SDKROOT="" GCC_VERSION=4.2 CLANG_CXX_LIBRARY="libstdc++" 
Exit code: 1
```

Yet better, of course, would be to fix 1.1.0 to build for PowerPC.

**Comment by barracuda156** [comment]
Related also: https://github.com/kwin/macdependency/issues/3
